services:
- docker
script:
- export SAVE=$PWD cnt="uburdsctr" slim=".slim"
- docker build -t ${cnt} .
- sudo ./docker-slim build --continue-after probe --http-probe ${cnt}
before_deploy:
- cd
- wget `curl -s https://api.github.com/repos/appc/docker2aci/releases | grep browser_download_url
  | head -n 1 | cut -d '"' -f 4` -O d2a.tar.gz
- tar -zxf d2a.tar.gz && rm d2a.tar.gz && d2a=`ls | grep "docker2aci*"` && d2a=`basename  $d2a`
  && alias d2a='${PWD}/${d2a}/docker2aci'
- docker save -o ${cnt}.slim.tar ${cnt}.slim
- "${PWD}/${d2a}/docker2aci ${cnt}.slim.tar"
- xz -9 -c ${cnt}.slim.tar > ${cnt}.slim.tar.xz
- docker login -e $QUAYE -u $QUAYL -p $QUAYP  quay.io
- docker tag ${cnt}${slim} quay.io/natostanco/$cnt
- docker push quay.io/natostanco/$cnt
deploy:
  provider: releases
  api_key:
    secure: U4MaUjIkqeGVT1rbV/8vYjJHvoq+ZQK786qSemXZcmPA2F83LldmHC/z6WjvI7JMcWZKEvPXgEYVMfEAyolDtpWBB72dq7pjgHmEOgQay8P/5mTAuq44qTox4TJCG7km05BEOK21ho1nsa57dJOWbTWMLAftR+vQSfuS32ONm6sqSuNT8gbH2b20idRZy8+egVJjE5BhkeD9o+KixGZbtKj44bCw99M9WdEMq29KUrlFK9ISck6iknjje9eXEXxTs7M9GV/0/zuOvn1TTOIWKtySMKjQI96lTIZ4Z8eDcJ27fLzBUEdMF/mSENFFqIQgZw/Q9P638wI39lybZyNFnYD5GwbyfbppBCuYWjmGqkhNN2ib6ObXmogXEdsW8A6HKYSx/9uPwbaJfqV0xorLQd/r4QVwc47o52IIaQFeLgvnMIC2/mMYOJZ6C/+cQiFtriV9t2dnwzDyupsuO66TiZ9RE49/LEojbHkmKRSJKsHSSVewU5k6Lx2qrDVeqlKSse3gUajTa6kKW7/nPwgEIAIdI/X13LA52ONdg/HCqB7M83Aum1mGm6JahTm6E2cTNgm/DtKGierqabvc/dnntaTeOxjVAXxggC7Ujwo31llZt27VBaWkWwYI/OXBsrx7kH0Xfr2fA2MtGOZcqiSR1d02vGXqXt+e1l2NGejxWlY=
  file:
  - "${cnt}.slim.tar.xz"
  - "${cnt}.slim-latest.aci"
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: HXlcSYSnmmrRuAqkssnoW+LtRrvfYqBLPADnGKx8eoCd+iT8flSWA+s8zQ1KPyIHY/v5ZqbZBySNGfw9ZPNT6nzqmnerBwrpInocMUuzi9Om2OPSmktK8IUUoXMIS4rpHtavwRW5FS25tozSwpNBCqeDNZGUr0ybrTD719JJsDTnwYncpnMQbAtXFyi2Z9tUZh89VGl9iffqPdoJ46i3qGYE7zgAmCWVFZdqHzIEmp+A3UMfV5XxEOFcRn8PS7XLtHIAbAtrczBVGBTyX2zthW18fVlirgBJlbBaQ4/B3w2FQwz8D10KGq57TIgYSi05AvhUJSb7fw9CelCJbaNRhnCUnSgXYK87ZNn+yoJzdoUY7U8P3AU8PI1SjOnET1G6ViCPrjQeJFt6SxWk0zo1adHptNgcrNWRbsmPy+QbwYTkPUPPhC3qUTD/XtESn9M860oPqK6eXkScbRPxARZmRKCD37XIzU5fJD9eQkIJF4Fm9PZHjBliM69P/KDmyBaR7WMcQuhG6H2s+qBhk/IonjxUVqIaoSma0RytjdyCgLTBdnNSLEGph6Bz/sm8axfPHSHFcAfSBfuOA+4+qIwDeYeIs/WuQJ5SaiNAry9eoY6b9bmYykiqY6qUjKTI9DnasR9Tyxtn5ALuSgOmsgM49qHRJu3NWT1e5lBdEABReso=
  - secure: ITEk4TL0TuP4S5024zwJ7CC//yng6Kh8L3MNriTUlD7L47giK5Omk/CsdjhF6vj9eBmmsAiv8Dh9A9bWzxXZbOIFw/V1bwhbeWnUf0P7LK9DGZpNkDxZNy7GfbeBd0IY+nmU4jVf2pgb/Xtq1drX9petFCGaIw91Pa7rQKDL6UsAcmDW9s9YWnXsHrsR6DzLR/kMjcYojNwZA6K3rM5d5GVWNMRod0jQIWO0rCsZY9tHzu3noNLUqzSAYcuLrMuFN/nr+vN/kaFUcnJlkAKs3bQuVKTAcn8vzZ7x0+k6ncTv8Ex0VTTQn62MiTlWxmY5CJmdGrThRxLp5rfGJeQbKA6QRy3RC+GaV2plb5g0bpv4my5llT9Fq6jsgU029cN9QC/YHJUGOgHuy9p0W0SjEiN1PwIk38hxZ68ITi5G9jDcED7Wem7OTXFXycCvfkTxKpUe4ThAj7e4r1VfZ/NnLFug4YMOkIluoHAQQ0RpPVLCB4P0tgvJipSVzrGhBMMUmSc53G7ZPnO9X3VmBchH2cSHjMjysmbgMVSrln1uLxFXjjd6kDuVirVlUjkZkjhqueP+NWlemh/uQaslxqjCibpfsoMwuQ7Gjk0nebZJZ+V/HZKiH5TWT/9zvb63e9PEpyPmenUxIkVBnVhwjtdXGkr4TDc/7QMBeLfeMPGU9b0=
  - secure: kJb+h2lkXItvxEOYwVOfG4ZhK2wIIjYs3dOd+OUhCg1b8p20qKdF8RSt7WaxEjH0MluwImH/oyPklFrj69dyNRlnP6o1+YVDSjIXtFimnwCAspVFy53Osycfm7n9NyOiAccugWE07pKaOgGi2+05gEXCxTSfawMWcq9OqNLV+LKaawCE6rH+hsmOMv9nB/6NXkg+wpQeSXIkW+mkxgkbHCcYJox5aibIkBjXufsCu1JvVoC7pVwRmRQlq72JIsTIy3NYmqaP3C2g65MAXn9Un8covTHF0wa4AI2AGx5sTxYQD9CbR/uq5PWhCp3xb2F50OzAxipJ4mpI5K1MFZcP3518CK0A0C2fH7BHsRAE1aQWJCXb0NPHHXNwp5+FMNV4yV/9w1TINSbwSM7jy3QOnUDKM1BGI8b64V+K43fre5nSkWO1MxQL2FnBG+Y8KGUanwQhW2lLKD30rECiC0hKIRobGpUzKnxeGiWeZAkXlOyt/ZOFfHMZauULO4/+KJuL0JYtTQcU59D3W/wcsVBJCsQ48ZzKVIoD4E7kIUrWHvNdIWcg6Tc7OXx+/L0jpgaLHUKzOS23/zHJfc+j+FqvjIEnWTF/YaemAIxEi3x0KhsUoAsqyax5kJ2qT8xeAJQO99u4YTWR4lJbccqi9TGieXd6B25asUooC9HiR92Tbzk=
